// Усі рядки інтерфейсу. Форми множини: Intl.PluralRules('uk') → one / few / many.
export const uk = {
  appName: 'Human Plus',
  tagline: 'Неофіційний клієнт для HUMAN Школа',
  unofficial:
    'Неофіційний застосунок. Не пов’язаний із компанією HUMAN. «Plus» означає надбудову: зручніший погляд на ті самі дані, а не платний тариф.',
  tabs: {
    today: 'Сьогодні',
    next: 'На наступний урок',
    tasks: 'Усі завдання',
    schedule: 'Розклад',
    grades: 'Оцінки',
  },
  nav: 'Розділи',
  buttons: {
    refresh: 'Оновити',
    download: 'Завантажити',
    zoom: 'Zoom',
    logout: 'Вийти',
    logoutWipe: 'Вийти й стерти дані',
    retry: 'Спробувати ще раз',
    login: 'Увійти',
    expand: 'Розгорнути',
    collapse: 'Згорнути',
    prevWeek: 'Попередній тиждень',
    nextWeek: 'Наступний тиждень',
    thisWeek: 'Цей тиждень',
    tabsAria: 'Розділи',
    about: 'Про застосунок',
    settings: 'Налаштування',
    close: 'Закрити',
    report: 'Повідомити про проблему',
    widget: 'Міні-віджет',
    prevDay: 'Попередній день',
    nextDay: 'Наступний день',
    mini: 'Міні-режим',
    fullMode: 'Розгорнути вікно',
    cancelLogin: 'Скасувати вхід',
  },
  states: {
    loginTitle: 'Увійдіть у HUMAN',
    loginText:
      'Відкриється справжня сторінка входу HUMAN. Застосунок не бачить і не зберігає ваш пароль.',
    loading: 'Завантаження…',
    empty: 'Немає завдань 🎉',
    emptyDay: 'Сьогодні немає уроків',
    emptyNext: 'Найближчих уроків із завданнями немає',
    sessionExpiredTitle: 'Сесія закінчилась, увійдіть знову',
    sessionExpiredText: 'Збережені дані лишаються на місці й з’являться після входу.',
    notStudentTitle: 'Додаток доступний лише для учнів',
    notStudentText: 'Цей акаунт не має ролі «учень», тож дані не показуються.',
    errorTitle: 'Помилка завантаження',
    errorText: 'Не вдалося отримати дані. Спробуйте ще раз.',
    offline: 'Немає зв’язку, показано збережені дані',
    paused: 'Автооновлення призупинено через помилки сервера. Натисніть «Оновити» пізніше.',
    checkingRole: 'Перевіряємо акаунт…',
    partial: 'Частину даних не вдалося розпізнати. Відкрийте їх у Human.',
    demo: 'Демо-дані',
    noHomework: 'Домашнього завдання немає',
    unsupportedBlock: 'Цей фрагмент завдання застосунок поки не вміє показувати.',
    noContent: 'Опис завдання порожній.',
    noGrades: 'Оцінок поки немає',
    gradesNote:
      'Оцінки за завантажений період (приблизно останні два тижні). Середні значення не рахуємо.',
  },
  units: { kb: 'КБ', mb: 'МБ' },
  blocks: {
    image: 'Зображення до завдання',
    formula: 'Формула',
    imageError: 'Не вдалося завантажити зображення.',
    opensInBrowser: 'відкриється в браузері',
    linkBlocked: 'небезпечну адресу не відкриваємо',
    saved: (name) => `Збережено в «Завантаження»: ${name}`,
    fileErrors: {
      error: 'Не вдалося завантажити файл.',
      demo: 'У демо-режимі файли не завантажуються.',
      big: 'Файл завеликий (понад 150 МБ).',
      blocked: 'Файли такого типу не зберігаємо.',
      offline: 'Немає зв’язку.',
    },
  },
  updatedAt: (t) => `Оновлено о ${t}`,
  today: 'Сьогодні',
  assigned: 'Що задано',
  greet: {
    night: 'Доброї ночі',
    morning: 'Доброго ранку',
    day: 'Добрий день',
    evening: 'Добрий вечір',
  },
  timeline: {
    now: (subject, left) => `Зараз: ${subject}. Лишилось ${left}`,
    next: (left) => `До наступного уроку: ${left}`,
    dayOver: 'Уроки на сьогодні завершено',
    pendingTotal: 'Невиконано',
  },
  tomorrow: 'Завтра',
  tomorrowBlock: 'На завтра',
  nextRest: 'Наступні уроки',
  status: {
    assigned: 'Видане',
    overdue: 'Прострочено',
    submitted: 'На перевірці',
    accepted: 'Прийнято',
    returned: 'Повернуто',
    unknown: 'Статус невідомий',
  },
  statusIcon: {
    assigned: '○',
    overdue: '!',
    submitted: '…',
    accepted: '✓',
    returned: '↩',
    unknown: '?',
  },
  filters: {
    status: 'Статус',
    subject: 'Предмет',
    group: 'Групувати',
    pending: 'Невиконані',
    all: 'Усі',
    done: 'Здані',
    allSubjects: 'Усі предмети',
    byDate: 'За датою',
    bySubject: 'За предметом',
    period: 'Період',
    range2w: '±2 тижні',
    rangeAll: 'Увесь завантажений',
    noDeadline: 'Без дедлайну',
  },
  lesson: {
    cancelled: 'Скасовано',
    rescheduled: 'Перенесено',
    replacement: 'Заміна',
    online: 'Онлайн',
    weekend: 'Вихідний',
    noTheme: 'Тему не вказано',
    noLessons: 'Немає уроків',
    materials: 'Заняття',
    projectedNote: 'Урок за розкладом. Тема й завдання з’являться, коли вчитель їх додасть.',
    lessonWord: 'урок',
    deadline: 'Здати до',
  },
  plural: {
    task: { one: 'завдання', few: 'завдання', many: 'завдань' },
    lesson: { one: 'урок', few: 'уроки', many: 'уроків' },
    material: { one: 'матеріал', few: 'матеріали', many: 'матеріалів' },
    minute: { one: 'хвилина', few: 'хвилини', many: 'хвилин' },
    hour: { one: 'година', few: 'години', many: 'годин' },
    pending: { one: 'невиконане', few: 'невиконані', many: 'невиконаних' },
  },
  settings: {
    title: 'Налаштування',
    notifyTitle: 'Сповіщення',
    data: 'Дані',
    theme: 'Тема',
    themeSystem: 'Як у системі',
    themeLight: 'Світла',
    themeDark: 'Темна',
    colors: 'Кольори',
    accentCustom: 'Свій акцентний колір',
    successColor: 'Колір «Прийнято»',
    dangerColor: 'Колір «Прострочено»',
    resetColors: 'Скинути кольори',
    notify: 'Нагадувати про завтрашні дедлайни',
    miniTitle: 'Міні-режим',
    mini: 'Компактне вікно поверх інших',
    miniHint: 'гаряча клавіша Ctrl+Shift+H',
    miniOpacity: 'Прозорість у міні-режимі',
    glassTitle: 'Вигляд',
    glass: 'Скляні ефекти',
    glassAuto: 'Авто',
    glassOn: 'Увімкнено',
    glassOff: 'Вимкнено',
    glassNote: 'Без прозорості вмикається автоматично, якщо в Windows вимкнені ефекти прозорості.',
  },
  widget: {
    title: 'Що задано на завтра',
    nothing: 'На завтра нічого не задано 🎉',
    tomorrowCount: (n) => `Завтра задано: ${n}`,
  },
  about: {
    title: 'Про застосунок',
    text: 'Human Plus — неофіційний клієнт для HUMAN Школа, лише для читання. Він показує домашні завдання, розклад і оцінки поточного учня. Застосунок не пов’язаний із компанією HUMAN, не здає завдань і не змінює даних.',
    privacy:
      'Дані зберігаються лише на цьому комп’ютері. Паролі й токени не зберігаються. Запити йдуть тільки на human.ua.',
    version: 'Версія',
  },
  loginFootnote:
    'Неофіційний застосунок. Вхід відбувається на сторінці HUMAN; пароль до нас не потрапляє.',
  report: { copied: 'Діагностику скопійовано в буфер. Вона не містить даних учня.' },
  notify: {
    title: 'Завтра дедлайн',
    body: (n, subjects) => `${n}: ${subjects}`,
  },
  menu: {
    file: 'Файл',
    view: 'Вигляд',
    help: 'Довідка',
    quit: 'Вийти із застосунку',
    reload: 'Оновити дані',
    toggleMini: 'Міні-режим',
    showWindow: 'Відкрити',
    zoomIn: 'Збільшити',
    zoomOut: 'Зменшити',
    zoomReset: 'Звичайний масштаб',
    fullscreen: 'На весь екран',
    undo: 'Скасувати',
    redo: 'Повторити',
    cut: 'Вирізати',
    copy: 'Копіювати',
    paste: 'Вставити',
    selectAll: 'Виділити все',
    edit: 'Редагування',
  },
  tray: { tooltip: (n) => (n ? `Human Plus — невиконаних: ${n}` : 'Human Plus') },
  errors: { generic: 'Щось пішло не так.' },
  days: { today: 'Сьогодні', tomorrow: 'Завтра' },
  grades: { subject: 'Предмет', grade: 'Оцінка', recent: 'Останні' },
  debug: { requests: (n) => `Запитів за останнє оновлення: ${n}` },
};
